/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Daza_
 */
public class RogerCardLogged extends javax.swing.JFrame {

    /**
     * Creates new form RogerCardLogged
     */
    public RogerCardLogged() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarEmailPanel1 = new javax.swing.JPanel();
        alterarEmailButton1 = new javax.swing.JButton();
        novoemailTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        antigoemailTextField1 = new javax.swing.JTextField();
        alterarSenhaPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        senhaTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        alterarDadosMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        excluirContaMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        alterarEmailButton1.setText("Alterar");
        alterarEmailButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEmailButton1ActionPerformed(evt);
            }
        });

        novoemailTextField2.setText("Novo Email:");
        novoemailTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                novoemailTextField2FocusGained(evt);
            }
        });
        novoemailTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoemailTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite o Novo Email");

        jLabel3.setText("Digite o Email Atual");

        antigoemailTextField1.setText("Email Atual:");
        antigoemailTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                antigoemailTextField1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout alterarEmailPanel1Layout = new javax.swing.GroupLayout(alterarEmailPanel1);
        alterarEmailPanel1.setLayout(alterarEmailPanel1Layout);
        alterarEmailPanel1Layout.setHorizontalGroup(
            alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarEmailPanel1Layout.createSequentialGroup()
                .addGroup(alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarEmailPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(alterarEmailButton1))
                    .addGroup(alterarEmailPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novoemailTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(antigoemailTextField1))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        alterarEmailPanel1Layout.setVerticalGroup(
            alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarEmailPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(antigoemailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoemailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(alterarEmailButton1)
                .addGap(57, 57, 57))
        );

        getContentPane().add(alterarEmailPanel1, "card2");

        jLabel2.setText("Digite a Nova Senha");

        senhaTextField1.setText("Senha:");
        senhaTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaTextField1FocusGained(evt);
            }
        });
        senhaTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");

        javax.swing.GroupLayout alterarSenhaPanel1Layout = new javax.swing.GroupLayout(alterarSenhaPanel1);
        alterarSenhaPanel1.setLayout(alterarSenhaPanel1Layout);
        alterarSenhaPanel1Layout.setHorizontalGroup(
            alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                .addGroup(alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(senhaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton2)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        alterarSenhaPanel1Layout.setVerticalGroup(
            alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
        );

        getContentPane().add(alterarSenhaPanel1, "card3");

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Configurações");

        alterarDadosMenuItem1.setText("Alterar Email");
        alterarDadosMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(alterarDadosMenuItem1);

        jMenuItem2.setText("Alterar Senha");
        jMenu3.add(jMenuItem2);

        excluirContaMenuItem3.setText("Excluir Conta");
        jMenu3.add(excluirContaMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarDadosMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_alterarDadosMenuItem1ActionPerformed

    private void novoemailTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoemailTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoemailTextField2ActionPerformed

    private void senhaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTextField1ActionPerformed

    private void senhaTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaTextField1FocusGained
        // TODO add your handling code here:
        senhaTextField1.selectAll();
    }//GEN-LAST:event_senhaTextField1FocusGained

    private void novoemailTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_novoemailTextField2FocusGained
        // TODO add your handling code here:
        novoemailTextField2.selectAll();
    }//GEN-LAST:event_novoemailTextField2FocusGained

    private void alterarEmailButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEmailButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_alterarEmailButton1ActionPerformed

    private void antigoemailTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_antigoemailTextField1FocusGained
        // TODO add your handling code here:
        antigoemailTextField1.selectAll();
    }//GEN-LAST:event_antigoemailTextField1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RogerCardLogged().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarDadosMenuItem1;
    private javax.swing.JButton alterarEmailButton1;
    private javax.swing.JPanel alterarEmailPanel1;
    private javax.swing.JPanel alterarSenhaPanel1;
    private javax.swing.JTextField antigoemailTextField1;
    private javax.swing.JMenuItem excluirContaMenuItem3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField novoemailTextField2;
    private javax.swing.JTextField senhaTextField1;
    // End of variables declaration//GEN-END:variables
}
