/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controllers.CreditCardController;
import Controllers.InvoiceController;
import Controllers.UserController;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Daza_
 */
public class RogerCardLogged extends javax.swing.JFrame {

    /**
     * Creates new form RogerCardLogged
     */
    public RogerCardLogged() throws ParseException {
        initComponents();
        
        mainPanel.setLayout(new CardLayout());
        mainPanel.add(alterarEmailPanel1, "alterarEmailPanel1");
        mainPanel.add(alterarSenhaPanel1, "alterarSenhaPanel1");
        mainPanel.add(excluirContaPanel1, "excluirContaPanel1");
        mainPanel.add(CartoesListPanel1, "CartoesListPanel1");
        mainPanel.add(pagarFaturaPanel1, "pagarFaturaPanel1");
        mainPanel.add(OpenInvoicePanel1, "OpenInvoicePanel1");
        mainPanel.add(closeInvoicePanel1, "closeInvoicePanel1");
        mainPanel.add(payInvoicePanel1, "payInvoicePanel1");
       
        MaskFormatter mascara;
        mascara = new MaskFormatter("##/##/####");
        mascara.setPlaceholderCharacter('_'); // Definindo um espaço reservado
        invoiceDueDateTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascara));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        alterarEmailPanel1 = new javax.swing.JPanel();
        alterarEmailButton1 = new javax.swing.JButton();
        novoemailTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        antigoemailTextField1 = new javax.swing.JTextField();
        avisoLabel4 = new javax.swing.JLabel();
        alterarSenhaPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        senhaNovaTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        senhaAntigaTextField2 = new javax.swing.JTextField();
        avisoLabel9 = new javax.swing.JLabel();
        excluirContaPanel1 = new javax.swing.JPanel();
        deleteAccountButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exclusaoTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        warningLabel9 = new javax.swing.JLabel();
        CartoesListPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textcartoesTextArea1 = new javax.swing.JTextArea();
        pagarFaturaPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        invoiceValueTextField1 = new javax.swing.JTextField();
        regFaturaButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        invoiceNumTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        invoiceDueDateTextField1 = new javax.swing.JFormattedTextField();
        OpenInvoicePanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textinvoiceopenTextArea1 = new javax.swing.JTextArea();
        closeInvoicePanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        closeInvoiceTextArea1 = new javax.swing.JTextArea();
        payInvoicePanel1 = new javax.swing.JPanel();
        invoiceTotalTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        applyDiscountCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        faturasCartaoMenu2 = new javax.swing.JMenu();
        registrarFaturaMenuItem3 = new javax.swing.JMenuItem();
        openInvoiceMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        closeInvoiceMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        alterarDadosMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        excluirContaMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cartoesMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, "card4");

        alterarEmailButton1.setText("Alterar");
        alterarEmailButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEmailButton1ActionPerformed(evt);
            }
        });

        novoemailTextField2.setText("Novo Email:");
        novoemailTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                novoemailTextField2FocusGained(evt);
            }
        });
        novoemailTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoemailTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite o Novo Email");

        jLabel3.setText("Digite o Email Atual");

        antigoemailTextField1.setText("Email Atual:");
        antigoemailTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                antigoemailTextField1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout alterarEmailPanel1Layout = new javax.swing.GroupLayout(alterarEmailPanel1);
        alterarEmailPanel1.setLayout(alterarEmailPanel1Layout);
        alterarEmailPanel1Layout.setHorizontalGroup(
            alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarEmailPanel1Layout.createSequentialGroup()
                .addGroup(alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarEmailPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(alterarEmailButton1)
                        .addGap(18, 18, 18)
                        .addComponent(avisoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alterarEmailPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(antigoemailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(novoemailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        alterarEmailPanel1Layout.setVerticalGroup(
            alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarEmailPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(antigoemailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoemailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(alterarEmailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterarEmailButton1)
                    .addComponent(avisoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(alterarEmailPanel1, "card2");

        alterarSenhaPanel1.setName("Alterar senha"); // NOI18N

        jLabel2.setText("Digite a Nova Senha");

        senhaNovaTextField1.setText("Nova senha:");
        senhaNovaTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaNovaTextField1FocusGained(evt);
            }
        });
        senhaNovaTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaNovaTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Digite a Senha Antiga");

        senhaAntigaTextField2.setText("Senha Atual");
        senhaAntigaTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaAntigaTextField2FocusGained(evt);
            }
        });

        javax.swing.GroupLayout alterarSenhaPanel1Layout = new javax.swing.GroupLayout(alterarSenhaPanel1);
        alterarSenhaPanel1.setLayout(alterarSenhaPanel1Layout);
        alterarSenhaPanel1Layout.setHorizontalGroup(
            alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                .addGroup(alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(avisoLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhaNovaTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senhaAntigaTextField2))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        alterarSenhaPanel1Layout.setVerticalGroup(
            alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarSenhaPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(senhaAntigaTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaNovaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(alterarSenhaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(avisoLabel9))
                .addGap(27, 27, 27))
        );

        getContentPane().add(alterarSenhaPanel1, "card3");

        deleteAccountButton1.setBackground(new java.awt.Color(255, 51, 51));
        deleteAccountButton1.setText("EXCLUIR CONTA");
        deleteAccountButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Para excluir a conta digite: \"CONFIRMAR EXCLUSAO\"  e clique no botão");

        javax.swing.GroupLayout excluirContaPanel1Layout = new javax.swing.GroupLayout(excluirContaPanel1);
        excluirContaPanel1.setLayout(excluirContaPanel1Layout);
        excluirContaPanel1Layout.setHorizontalGroup(
            excluirContaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excluirContaPanel1Layout.createSequentialGroup()
                .addGroup(excluirContaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(excluirContaPanel1Layout.createSequentialGroup()
                        .addContainerGap(315, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(excluirContaPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(deleteAccountButton1)
                        .addGroup(excluirContaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(excluirContaPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel8))
                            .addGroup(excluirContaPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(warningLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(excluirContaPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(exclusaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(excluirContaPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        excluirContaPanel1Layout.setVerticalGroup(
            excluirContaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, excluirContaPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exclusaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(excluirContaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAccountButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(warningLabel9))
                .addGap(35, 35, 35))
        );

        deleteAccountButton1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(excluirContaPanel1, "card5");

        textcartoesTextArea1.setEditable(false);
        textcartoesTextArea1.setColumns(20);
        textcartoesTextArea1.setRows(5);
        jScrollPane1.setViewportView(textcartoesTextArea1);

        javax.swing.GroupLayout CartoesListPanel1Layout = new javax.swing.GroupLayout(CartoesListPanel1);
        CartoesListPanel1.setLayout(CartoesListPanel1Layout);
        CartoesListPanel1Layout.setHorizontalGroup(
            CartoesListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartoesListPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        CartoesListPanel1Layout.setVerticalGroup(
            CartoesListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartoesListPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(CartoesListPanel1, "card6");

        jLabel10.setText("Valor da Fatura:");

        regFaturaButton1.setText("Registrar");
        regFaturaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFaturaButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Número de Pagamento da Fatura:");

        jLabel9.setText("Data de Vencimento da Fatura:");

        invoiceDueDateTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceDueDateTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pagarFaturaPanel1Layout = new javax.swing.GroupLayout(pagarFaturaPanel1);
        pagarFaturaPanel1.setLayout(pagarFaturaPanel1Layout);
        pagarFaturaPanel1Layout.setHorizontalGroup(
            pagarFaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagarFaturaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pagarFaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceNumTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pagarFaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceValueTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(pagarFaturaPanel1Layout.createSequentialGroup()
                .addGroup(pagarFaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagarFaturaPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(regFaturaButton1))
                    .addGroup(pagarFaturaPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pagarFaturaPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(invoiceDueDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pagarFaturaPanel1Layout.setVerticalGroup(
            pagarFaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagarFaturaPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pagarFaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pagarFaturaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNumTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceValueTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceDueDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(regFaturaButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(pagarFaturaPanel1, "card7");

        textinvoiceopenTextArea1.setEditable(false);
        textinvoiceopenTextArea1.setColumns(20);
        textinvoiceopenTextArea1.setRows(5);
        jScrollPane2.setViewportView(textinvoiceopenTextArea1);

        javax.swing.GroupLayout OpenInvoicePanel1Layout = new javax.swing.GroupLayout(OpenInvoicePanel1);
        OpenInvoicePanel1.setLayout(OpenInvoicePanel1Layout);
        OpenInvoicePanel1Layout.setHorizontalGroup(
            OpenInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(OpenInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OpenInvoicePanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        OpenInvoicePanel1Layout.setVerticalGroup(
            OpenInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(OpenInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OpenInvoicePanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(OpenInvoicePanel1, "card8");

        closeInvoiceTextArea1.setEditable(false);
        closeInvoiceTextArea1.setColumns(20);
        closeInvoiceTextArea1.setRows(5);
        jScrollPane3.setViewportView(closeInvoiceTextArea1);

        javax.swing.GroupLayout closeInvoicePanel1Layout = new javax.swing.GroupLayout(closeInvoicePanel1);
        closeInvoicePanel1.setLayout(closeInvoicePanel1Layout);
        closeInvoicePanel1Layout.setHorizontalGroup(
            closeInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(closeInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(closeInvoicePanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        closeInvoicePanel1Layout.setVerticalGroup(
            closeInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(closeInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(closeInvoicePanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(closeInvoicePanel1, "card9");

        jLabel11.setText("Valor Total da Fatura");

        applyDiscountCheckBox1.setText("Aplicar Desconto");
        applyDiscountCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyDiscountCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payInvoicePanel1Layout = new javax.swing.GroupLayout(payInvoicePanel1);
        payInvoicePanel1.setLayout(payInvoicePanel1Layout);
        payInvoicePanel1Layout.setHorizontalGroup(
            payInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payInvoicePanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(payInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payInvoicePanel1Layout.createSequentialGroup()
                        .addComponent(invoiceTotalTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(applyDiscountCheckBox1))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        payInvoicePanel1Layout.setVerticalGroup(
            payInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payInvoicePanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payInvoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceTotalTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyDiscountCheckBox1))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        getContentPane().add(payInvoicePanel1, "card10");

        faturasCartaoMenu2.setText("Faturas");

        registrarFaturaMenuItem3.setText("Registrar Contas a pagar");
        registrarFaturaMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarFaturaMenuItem3ActionPerformed(evt);
            }
        });
        faturasCartaoMenu2.add(registrarFaturaMenuItem3);

        openInvoiceMenuItem1.setText("Visualizar Faturas em Aberto");
        openInvoiceMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openInvoiceMenuItem1ActionPerformed(evt);
            }
        });
        faturasCartaoMenu2.add(openInvoiceMenuItem1);

        jMenuItem1.setText("Pagar Fatura");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        faturasCartaoMenu2.add(jMenuItem1);

        closeInvoiceMenuItem3.setText("Visualizar Faturas Fechadas");
        closeInvoiceMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeInvoiceMenuItem3ActionPerformed(evt);
            }
        });
        faturasCartaoMenu2.add(closeInvoiceMenuItem3);

        jMenuBar1.add(faturasCartaoMenu2);

        jMenu3.setText("Configurações");

        alterarDadosMenuItem1.setText("Alterar Email");
        alterarDadosMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(alterarDadosMenuItem1);

        jMenuItem2.setText("Alterar Senha");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        excluirContaMenuItem3.setText("Excluir Conta");
        excluirContaMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirContaMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(excluirContaMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Cartões");

        cartoesMenuItem1.setText("Visualizar cartões");
        cartoesMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartoesMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(cartoesMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarDadosMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosMenuItem1ActionPerformed
        // TODO add your handling code here: 
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "alterarEmailPanel1");
    }//GEN-LAST:event_alterarDadosMenuItem1ActionPerformed

    private void novoemailTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoemailTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoemailTextField2ActionPerformed

    private void senhaNovaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaNovaTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaNovaTextField1ActionPerformed

    private void senhaNovaTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaNovaTextField1FocusGained
        // TODO add your handling code here:
        senhaNovaTextField1.selectAll();
    }//GEN-LAST:event_senhaNovaTextField1FocusGained

    private void novoemailTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_novoemailTextField2FocusGained
        // TODO add your handling code here:
        novoemailTextField2.selectAll();
    }//GEN-LAST:event_novoemailTextField2FocusGained

    private void alterarEmailButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEmailButton1ActionPerformed
        // TODO add your handling code here:
        String emailAntigo = antigoemailTextField1.getText();
        String emailNovo = novoemailTextField2.getText();
        
        UserController userController = new UserController();
        try {
            if(userController.alterarEmail(emailNovo, emailAntigo)){
                avisoLabel4.setText("Email Alterado com Sucesso");
            }else{
                avisoLabel4.setText("Erro ao Alterar o email");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_alterarEmailButton1ActionPerformed

    private void antigoemailTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_antigoemailTextField1FocusGained
        // TODO add your handling code here:
        antigoemailTextField1.selectAll();
    }//GEN-LAST:event_antigoemailTextField1FocusGained

    private void senhaAntigaTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaAntigaTextField2FocusGained
        // TODO add your handling code here:
        senhaAntigaTextField2.selectAll();
    }//GEN-LAST:event_senhaAntigaTextField2FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String senhaAntiga = senhaAntigaTextField2.getText();
        
        String senhaNova  = senhaNovaTextField1.getText();
        UserController userController = new UserController();
        try {
            if(userController.alterarSenha(senhaNova, senhaAntiga)){
                avisoLabel9.setText("Senha Alterada com Sucesso");
                
            }else{
                avisoLabel9.setText("Erro ao alterar a senha");
            }
        } catch (SQLException ex) {
            Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "alterarSenhaPanel1");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void deleteAccountButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButton1ActionPerformed
        // TODO add your handling code here:
        String deleteAccount = exclusaoTextField1.getText();
        if(deleteAccount.equals("CONFIRMAR EXCLUSAO")){
            UserController userController = new UserController();
            try {
                if(userController.excluirConta()){
                    RogerCardGUI rogerCardGUI = new RogerCardGUI();
                    rogerCardGUI.setVisible(true);
                    this.dispose();
                }else{
                    warningLabel9.setText("ERRO");
                }
            } catch (SQLException ex) {
                Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_deleteAccountButton1ActionPerformed

    private void excluirContaMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirContaMenuItem3ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "excluirContaPanel1");
    }//GEN-LAST:event_excluirContaMenuItem3ActionPerformed

    private void cartoesMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartoesMenuItem1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "CartoesListPanel1");
        
        CreditCardController creditCardController = new CreditCardController();
        String printCard = "";
        try {
            printCard = creditCardController.printCard();
        } catch (SQLException ex) {
            Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
        }
        textcartoesTextArea1.setText(printCard);
        
    }//GEN-LAST:event_cartoesMenuItem1ActionPerformed

    private void registrarFaturaMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarFaturaMenuItem3ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "pagarFaturaPanel1");
    }//GEN-LAST:event_registrarFaturaMenuItem3ActionPerformed

    private void regFaturaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFaturaButton1ActionPerformed
        // TODO add your handling code here:
        String invoiceNumber = invoiceNumTextField1.getText();
        String value = invoiceValueTextField1.getText();
        Double invoicevalue = 0.0;
        
        try {
        Double invoiceValue = Double.parseDouble(value); 
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Valor inválido para a fatura", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
        Double invoiceValue = Double.parseDouble(value); 
        String date = invoiceDueDateTextField1.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate invoiceDueDate = null;
        try {
        // Tenta converter a data para LocalDate
        invoiceDueDate = LocalDate.parse(date, formatter);
    } catch (Exception e) {
        // Se der erro na conversão, imprime a exceção
        JOptionPane.showMessageDialog(this, "Data inválida! O formato correto é dd/MM/yyyy", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String status = "ABERTA";
    //AJUSTAR O STATUS
    // Cria o controlador e chama o método para criar a fatura
    InvoiceController invoiceController = new InvoiceController();
    try {
        invoiceController.createInvoice(invoiceNumber, invoiceValue, invoiceDueDate, null, status);
        System.out.println("REGISTRADO COM SUCESSO");
    } catch (SQLException e) {
        // Caso haja erro no banco de dados, imprime a exceção
        System.out.println("Erro ao registrar a fatura: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Erro ao registrar fatura. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
        
       
    
       
        
    }//GEN-LAST:event_regFaturaButton1ActionPerformed

    private void invoiceDueDateTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceDueDateTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_invoiceDueDateTextField1ActionPerformed

    private void openInvoiceMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openInvoiceMenuItem1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "OpenInvoicePanel1");
        
        InvoiceController invoiceController = new InvoiceController();
        String printInvoiceOpen = "";
        try {
            printInvoiceOpen = invoiceController.printOpenInvoice();
        } catch (SQLException ex) {
            Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
        }
        textinvoiceopenTextArea1.setText(printInvoiceOpen);
        
    }//GEN-LAST:event_openInvoiceMenuItem1ActionPerformed

    private void closeInvoiceMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeInvoiceMenuItem3ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "closeInvoicePanel1");
        
        InvoiceController invoiceController = new InvoiceController();
        String printInvoiceClose = "";
        try {
            printInvoiceClose = invoiceController.printCloseInvoice();
        } catch (SQLException ex) {
            Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
        }
        closeInvoiceTextArea1.setText(printInvoiceClose);
        
    }//GEN-LAST:event_closeInvoiceMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "payInvoicePanel1");
        
        InvoiceController invoiceController = new InvoiceController();
        try {
            Double invoiceValue = invoiceController.invoiceValue();
            invoiceTotalTextField1.setText(invoiceValue.toString());
            
        } catch (SQLException ex) {
            Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void applyDiscountCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyDiscountCheckBox1ActionPerformed
        // TODO add your handling code here:
        
        if(applyDiscountCheckBox1.isSelected()){
            
        }
    }//GEN-LAST:event_applyDiscountCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RogerCardLogged.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RogerCardLogged().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(RogerCardLogged.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartoesListPanel1;
    private javax.swing.JPanel OpenInvoicePanel1;
    private javax.swing.JMenuItem alterarDadosMenuItem1;
    private javax.swing.JButton alterarEmailButton1;
    private javax.swing.JPanel alterarEmailPanel1;
    private javax.swing.JPanel alterarSenhaPanel1;
    private javax.swing.JTextField antigoemailTextField1;
    private javax.swing.JCheckBox applyDiscountCheckBox1;
    private javax.swing.JLabel avisoLabel4;
    private javax.swing.JLabel avisoLabel9;
    private javax.swing.JMenuItem cartoesMenuItem1;
    private javax.swing.JMenuItem closeInvoiceMenuItem3;
    private javax.swing.JPanel closeInvoicePanel1;
    private javax.swing.JTextArea closeInvoiceTextArea1;
    private javax.swing.JButton deleteAccountButton1;
    private javax.swing.JMenuItem excluirContaMenuItem3;
    private javax.swing.JPanel excluirContaPanel1;
    private javax.swing.JTextField exclusaoTextField1;
    private javax.swing.JMenu faturasCartaoMenu2;
    private javax.swing.JFormattedTextField invoiceDueDateTextField1;
    private javax.swing.JTextField invoiceNumTextField1;
    private javax.swing.JTextField invoiceTotalTextField1;
    private javax.swing.JTextField invoiceValueTextField1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField novoemailTextField2;
    private javax.swing.JMenuItem openInvoiceMenuItem1;
    private javax.swing.JPanel pagarFaturaPanel1;
    private javax.swing.JPanel payInvoicePanel1;
    private javax.swing.JButton regFaturaButton1;
    private javax.swing.JMenuItem registrarFaturaMenuItem3;
    private javax.swing.JTextField senhaAntigaTextField2;
    private javax.swing.JTextField senhaNovaTextField1;
    private javax.swing.JTextArea textcartoesTextArea1;
    private javax.swing.JTextArea textinvoiceopenTextArea1;
    private javax.swing.JLabel warningLabel9;
    // End of variables declaration//GEN-END:variables
}
